name: Generate and Deploy Anilist Profile Images

on:
  schedule:
    - cron: '0 */3 * * *' 
  workflow_dispatch: 

jobs:
  build-and-deploy-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.9' 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate Images
        env:
          ANILIST_USERNAME: ${{ secrets.ANILIST_USERNAME }}
          ANILIST_TOKEN: ${{ secrets.ANILIST_TOKEN }}
        run: python generate_images_script.py 

      - name: Commit and Push Images
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add last_anime.png last_manga.png *.ttf # Add font files if they aren't already tracked
          # Commit only if there are changes to the PNG files
          if ! git diff --staged --quiet -- last_anime.png last_manga.png; then
            git commit -m "Update Anilist profile images"
            git push
          else
            echo "No changes to profile images to commit."
          fi